#%RAML 0.8

title: Sitemap Service
version: v1
baseUri: http://dev.sitemaps.services.bauer-media.internal/
mediaType: application/xml
/{version}/{site}:
  displayName: Get index sitemap
  description: Get index sitemap for the provided site.
  uriParameters:
    version:
        displayName: version
        type: string
        description: Version. Note that this parameter is not used yet
        example: v1
    site:
        displayName: site
        type: string
        description: Site code.
        example: dolly
  get:
    description: |
        Get index sitemap.
    responses:
      200:
        body:
            application/xml:
                example: !include examples/indexSitemapResult.xml
/{version}/{site}/{section}:
  displayName: Get section sitemap
  description: Get section sitemap for the provided site and section. The section can be normal sections or news.
  uriParameters:
    version:
        displayName: version
        type: string
        description: Version. Note that this parameter is not used yet
        example: v1
    site:
        displayName: site
        type: string
        description: Site code.
        example: dolly
    section:
        displayName: section
        type: string
        description: section url name.
        example: fashion, win, news
  get:
    description: |
        Get section sitemap.
    responses:
      200:
        body:
            application/xml:
                example: !include examples/sectionSitemapResult.xml